import Assets from './Assets';

export default {
	JavaScript: { logo: Assets.JavaScript, name: 'JavaScript' },
	TypeScript: { logo: Assets.TypeScript, name: 'TypeScript' },
	Dart: { logo: Assets.Dart, name: 'Dart' },
	Kotlin: { logo: Assets.Kotlin, name: 'Kotlin' },
	Java: { logo: Assets.Java, name: 'Java' },
	Python: { logo: Assets.Python, name: 'Python' },
	Csharp: { logo: Assets.Csharp, name: 'C#' },
	NodeJs: { logo: Assets.NodeJs, name: 'Node Js' },
	Deno: { logo: Assets.Deno, name: 'Deno', inverted: true },
	VueJs: { logo: Assets.VueJs, name: 'Vue Js' },
	ReactJs: { logo: Assets.ReactJs, name: 'React Js' },
	Svelte: { logo: Assets.Svelte, name: 'Svelte' },
	Angular: { logo: Assets.Angular, name: 'Angular' },
	Flutter: { logo: Assets.Flutter, name: 'Flutter' },
	Xamarin: { logo: Assets.Xamarin, name: 'Xamarin' },
	Electron: { logo: Assets.Electron, name: 'Electron' },
	SolidJs: { logo: Assets.SolidJs, name: 'Solid Js' },
	Quasar: { logo: Assets.Quasar, name: 'Quasar' },
	Nuxt: { logo: Assets.Nuxt, name: 'Nuxt' },
	Android: { logo: Assets.Android, name: 'Android' },
	ExpressJs: { logo: Assets.ExpressJs, name: 'Express Js' },
	Fastify: { logo: Assets.Fastify, name: 'Fastify', inverted: true },
	NestJs: { logo: Assets.NestJs, name: 'Nest Js' },
	AdonisJs: { logo: Assets.AdonisJs, name: 'Adonis Js' },
	PostgreSQL: { logo: Assets.PostgreSQL, name: 'PostgreSQL' },
	Firebase: { logo: Assets.Firebase, name: 'Firebase' },
	Redis: { logo: Assets.Redis, name: 'Redis' },
	MongoDB: { logo: Assets.MongoDB, name: 'MongoDB' },
	Sass: { logo: Assets.Sass, name: 'Sass' },
	Tailwind: { logo: Assets.Tailwind, name: 'Tailwind' },
	CSS: { logo: Assets.CSS, name: 'CSS' },
	HTML: { logo: Assets.HTML, name: 'HTML' },
	Photoshop: { logo: Assets.Photoshop, name: 'Adobe Photoshop' },
	Illustrator: { logo: Assets.Illustrator, name: 'Adobe Illustrator' },
	AfterEffects: { logo: Assets.AfterEffects, name: 'Adobe After Effects' },
	Premiere: { logo: Assets.Premiere, name: 'Adobe Premiere Pro' },
	AWS: { logo: Assets.AWS, name: 'AWS' },
	Bootstrap: { logo: Assets.Bootstrap, name: 'Bootstrap' },
	C: { logo: Assets.C, name: 'C' },
	Cpp: { logo: Assets.Cpp, name: 'C++' },
	Celery: { logo: Assets.Celery, name: 'Celery' },
	Django: { logo: Assets.Django, name: 'Django' },
	Docker: { logo: Assets.Docker, name: 'Docker' },
	FastApi: { logo: Assets.FastApi, name: 'FastApi' },
	Flask: { logo: Assets.Flask, name: 'Flask', inverted: true },
	Go: { logo: Assets.Go, name: 'Go' },
	Kafka: { logo: Assets.Kafka, name: 'Kafka', inverted: true },
	Kubernetes: { logo: Assets.Kubernetes, name: 'Kubernetes' },
	Neo4j: { logo: Assets.Neo4j, name: 'Neo4j' },
	Nginx: { logo: Assets.Nginx, name: 'Nginx' },
	Pandas: { logo: Assets.Pandas, name: 'Pandas' },
	RabbitMQ: { logo: Assets.RabbitMQ, name: 'RabbitMQ' },
	Rust: { logo: Assets.Rust, name: 'Rust', inverted: true },
	Scrapy: { logo: Assets.Scrapy, name: 'Scrapy' },
	Selenium: { logo: Assets.Selenium, name: 'Selenium' }
};
